name: Backend Build and Test

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest  # Use an appropriate runner (e.g., ubuntu-latest, windows-latest, macos-latest)

    steps:
    - uses: actions/checkout@v3  # Check out your repository's code

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version


    - name: Backend dependencies
      run: npm install  # Install project dependencies
      working-directory: ./backend

    - name: Call the backend tests
      run: npm test
      working-directory: ./backend


    - name: Lint the Vue App and save the output to a file


      