name: Backend Build and Test

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest  # Use an appropriate runner (e.g., ubuntu-latest, windows-latest, macos-latest)

    steps:
    - uses: actions/checkout@v3  # Check out your repository's code

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Create .env file
      run: |
        touch ./backend/.env
        echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" >> ./backend/.env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./backend/.env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> ./backend/.env


    - name: Backend dependencies
      run: npm install  # Install project dependencies
      working-directory: ./backend
    

    - name: Call the backend tests
      run: npm test
      working-directory: ./backend




      