name: Node.js CI

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest  # Use an appropriate runner (e.g., ubuntu-latest, windows-latest, macos-latest)

    steps:
    - uses: actions/checkout@v2  # Check out your repository's code

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name : Navigate to the directory
      run: cd backend # Install project dependencies

    - name: Install dependencies
      run: npm install  # Install project dependencies
      working-directory: ./backend
    
    - name: Run tests
      run: npm test  # Run tests using npm test script
      working-directory: ./backend